language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
  - "2.7"

install:
  - "pip install six"
  - "pip install mock"
  - "pip install parserutils"
  - "pip install frozendict"
  - "pip install coveralls"

script:
  coverage run --source=gis_metadata -m unittest gis_metadata.tests.tests

after_success:
  coveralls